In [16]:
from tensorflow.keras.preprocessing.text import one_hot

In [17]:
#sentences
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good']

In [18]:
#define the vocabulury size
voc_size=10000

In [19]:
### one hot representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[5086, 2919, 8698, 3203],
 [5086, 2919, 8698, 8842],
 [5086, 3630, 8698, 1791],
 [6779, 6537, 3158, 3655, 9618],
 [6779, 6537, 3158, 3655, 1661],
 [3785, 5086, 615, 8698, 7971],
 [6086, 9688, 5808, 3655]]

In [20]:
#word embeddings representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [21]:
import numpy as np

In [22]:
sent_length=8

In [23]:
embed_doc=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embed_doc)

[[   0    0    0    0 5086 2919 8698 3203]
 [   0    0    0    0 5086 2919 8698 8842]
 [   0    0    0    0 5086 3630 8698 1791]
 [   0    0    0 6779 6537 3158 3655 9618]
 [   0    0    0 6779 6537 3158 3655 1661]
 [   0    0    0 3785 5086  615 8698 7971]
 [   0    0    0    0 6086 9688 5808 3655]]


In [24]:
#feature representation
dim=10

In [25]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [26]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.predict(embed_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 393ms/step


array([[[-0.04432905,  0.02103385, -0.02448628,  0.01780324,
         -0.04580264,  0.0234084 , -0.04588665,  0.03708974,
         -0.02840867, -0.03870066],
        [-0.04432905,  0.02103385, -0.02448628,  0.01780324,
         -0.04580264,  0.0234084 , -0.04588665,  0.03708974,
         -0.02840867, -0.03870066],
        [-0.04432905,  0.02103385, -0.02448628,  0.01780324,
         -0.04580264,  0.0234084 , -0.04588665,  0.03708974,
         -0.02840867, -0.03870066],
        [-0.04432905,  0.02103385, -0.02448628,  0.01780324,
         -0.04580264,  0.0234084 , -0.04588665,  0.03708974,
         -0.02840867, -0.03870066],
        [-0.04857218, -0.01150932, -0.0137971 ,  0.0335137 ,
         -0.00182815, -0.03700702, -0.02060246, -0.02071935,
          0.035981  ,  0.02581405],
        [ 0.02114633, -0.02541143, -0.01747767,  0.00841901,
          0.01826838, -0.02002473,  0.02193803,  0.02038666,
         -0.02641876, -0.01917508],
        [-0.00190036, -0.02186211, -0.03139966,  0.0